loam_interface:
  ros__parameters:
    use_sim_time: True
    loam_odometry_topic: "pslam/imu_odom"
    registered_scan_topic: "pslam/aligned_scan_cloud"
    map_cloud_topic: "pslam/lio_map_cloud"
    odom_frame: "odom"
    base_frame: "base_footprint"
    lidar_frame: "mid360"
    robot_base_frame: "base_link"

lio_3d_node:
  ros__parameters:
    use_sim_time: True
    lidar_type: "livox"
    use_as_localizer: False
    map_cloud_dir: $(find-pkg-share scorpio_nav_bringup)/maps/318
    param_files_dir: $(find-pkg-share scorpio_nav_bringup)/params

    pointcloud_topic: "livox/lidar"
    imu_topic: "livox/imu"

    imu_pose_topic: "pslam/imu_pose"
    imu_odom_topic: "pslam/imu_odom"
    lio_map_cloud_topic: "pslam/lio_map_cloud"
    aligned_scan_cloud_topic: "pslam/aligned_scan_cloud"
    deskewed_scan_cloud_topic: "pslam/deskewed_scan_cloud"

    odom_frame: "pslam/odom"
    imu_frame: "pslam/mid360_imu"
    publish_tf: false  # Whether to publish TF transform from `odom_frame` to `imu_frame`

slam_3d_node:
  ros__parameters:
    use_sim_time: True
    map_cloud_dir: "tmp/pslam_data/"
    param_files_dir: $(find-pkg-share scorpio_nav_bringup)/params

    imu_pose_topic: "pslam/imu_pose"
    deskewed_scan_cloud_topic: "pslam/deskewed_scan_cloud"

    filtered_map_cloud_topic: "pslam/filtered_map_cloud"
    graph_nodes_topic: "pslam/pose_graph_nodes"
    odom_edges_topic: "pslam/pose_graph_odom_edges"
    loop_edges_topic: "pslam/pose_graph_loop_edges"

    map_frame: "pslam/map"
    # odometry and imu frames are defined in lio_3d_config.yaml
    publish_tf: false  # Whether to publish TF transform from `map_frame` to `odom_frame`

terrain_analysis:
  ros__parameters:
    odom_frame: "odom"
    lidar_frame: "mid360"
    scan_voxel_size: 0.05
    decay_time: 2.0
    no_decay_dis: 4.0
    clearing_dis: 8.0
    use_sorting: true
    quantile_z: 0.25
    consider_drop: false
    limit_ground_lift: false
    max_ground_lift: 0.15
    clear_dy_obs: false
    min_dy_obs_dis: 0.3
    abs_dy_obs_rel_z_thre: 0.2
    min_dy_obs_vfov: -16.0
    max_dy_obs_vfov: 16.0
    min_dy_obs_point_num: 1
    min_out_of_fov_point_num: 2
    obstacle_height_thre: 0.2
    no_data_obstacle: false
    no_data_block_skip_num: 0
    min_block_point_num: 10
    vehicle_height: 1.5
    min_rel_z: -1.5
    max_rel_z: 0.2
    dis_ratio_z: 0.2
    voxel_point_update_thre: 100
    voxel_time_update_thre: 2.0

terrain_analysis_ext:
  ros__parameters:
    odom_frame: odom
    lidar_frame: mid360
    terrain_voxel_size: 2.0
    terrain_voxel_width: 41
    planar_voxel_size: 0.4
    planar_voxel_width: 101
    voxel_point_count_thre: 100
    ground_elevation_thre: 0.5
    use_terrain_dyn_thre: 1.5
    check_terrain_conn: true
    terrain_under_vehicle: -0.75
    ceiling_filtering_thre: 2.0
    local_terrain_map_radius: 4.0
    downsize_filter_corner: 0.2
    downsize_filter_surface: 0.1
    point_decay_period: 10
    point_decay_ratio: 0.5
    vertical_angle_thre: 0.0
    max_terrain_angle: 30.0
    ground_z_thre: 0.1
